[package]
name = "greek_number"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Lucy Jialin Lu <luxxxlucy@gmail.com>"]
include = ["src/*", "Cargo.toml", "README.md", "LICENSE"]
description = "Convert numbers to Greek number strings"

[dependencies]
